/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinal;

/**
 * Layered pane principal. contiene los elementos de UI y a la mesa de pool
 *
 * @author Keyteer
 * @author segonzalez2021
 * @version versión 0.1, 27 de noviembre de 2022
 * @see MesaPool
 */
public class PanelPrincipal extends javax.swing.JLayeredPane {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mesaPool1 = new proyectofinal.MesaPool();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(mesaPool1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private proyectofinal.MesaPool mesaPool1;
    // End of variables declaration//GEN-END:variables
}
